// Display names for IATA airport codes
export const AIRPORT_INFO = {
    LHR: { name: 'Heathrow', city: 'London', country: 'UK' },
    LGW: { name: 'Gatwick', city: 'London', country: 'UK' },
    STN: { name: 'Stansted', city: 'London', country: 'UK' },
    LAX: { name: 'Los Angeles', city: 'Los Angeles', country: 'USA' },
    JFK: { name: 'JFK', city: 'New York', country: 'USA' },
    EWR: { name: 'Newark', city: 'New York', country: 'USA' },
    ORD: { name: "O'Hare", city: 'Chicago', country: 'USA' },
    ATL: { name: 'Hartsfield-Jackson', city: 'Atlanta', country: 'USA' },
    SFO: { name: 'San Francisco', city: 'San Francisco', country: 'USA' },
    MIA: { name: 'Miami', city: 'Miami', country: 'USA' },
    BOS: { name: 'Logan', city: 'Boston', country: 'USA' },
    SEA: { name: 'Seattle-Tacoma', city: 'Seattle', country: 'USA' },
    DFW: { name: 'Dallas Fort Worth', city: 'Dallas', country: 'USA' },
    DXB: { name: 'Dubai', city: 'Dubai', country: 'UAE' },
    AUH: { name: 'Abu Dhabi', city: 'Abu Dhabi', country: 'UAE' },
    DOH: { name: 'Hamad', city: 'Doha', country: 'QA' },
    FRA: { name: 'Frankfurt', city: 'Frankfurt', country: 'DE' },
    MUC: { name: 'Munich', city: 'Munich', country: 'DE' },
    CDG: { name: 'Charles de Gaulle', city: 'Paris', country: 'FR' },
    ORY: { name: 'Orly', city: 'Paris', country: 'FR' },
    AMS: { name: 'Schiphol', city: 'Amsterdam', country: 'NL' },
    ZRH: { name: 'Zurich', city: 'Zurich', country: 'CH' },
    GVA: { name: 'Geneva', city: 'Geneva', country: 'CH' },
    BCN: { name: 'El Prat', city: 'Barcelona', country: 'ES' },
    MAD: { name: 'Barajas', city: 'Madrid', country: 'ES' },
    FCO: { name: 'Fiumicino', city: 'Rome', country: 'IT' },
    MXP: { name: 'Malpensa', city: 'Milan', country: 'IT' },
    IST: { name: 'Istanbul', city: 'Istanbul', country: 'TR' },
    SIN: { name: 'Changi', city: 'Singapore', country: 'SG' },
    HKG: { name: 'Hong Kong', city: 'Hong Kong', country: 'HK' },
    NRT: { name: 'Narita', city: 'Tokyo', country: 'JP' },
    HND: { name: 'Haneda', city: 'Tokyo', country: 'JP' },
    ICN: { name: 'Incheon', city: 'Seoul', country: 'KR' },
    BKK: { name: 'Suvarnabhumi', city: 'Bangkok', country: 'TH' },
    KUL: { name: 'Kuala Lumpur', city: 'Kuala Lumpur', country: 'MY' },
    SYD: { name: 'Kingsford Smith', city: 'Sydney', country: 'AU' },
    MEL: { name: 'Melbourne', city: 'Melbourne', country: 'AU' },
    BNE: { name: 'Brisbane', city: 'Brisbane', country: 'AU' },
    PER: { name: 'Perth', city: 'Perth', country: 'AU' },
    BOM: { name: 'Chhatrapati Shivaji', city: 'Mumbai', country: 'IN' },
    DEL: { name: 'Indira Gandhi', city: 'Delhi', country: 'IN' },
    HYD: { name: 'Rajiv Gandhi', city: 'Hyderabad', country: 'IN' },
    BLR: { name: 'Kempegowda', city: 'Bengaluru', country: 'IN' },
    MAA: { name: 'Chennai', city: 'Chennai', country: 'IN' },
    CCU: { name: 'Netaji Subhas Chandra Bose', city: 'Kolkata', country: 'IN' },
    YYZ: { name: 'Pearson', city: 'Toronto', country: 'CA' },
    YVR: { name: 'Vancouver', city: 'Vancouver', country: 'CA' },
    YUL: { name: 'Montréal-Trudeau', city: 'Montréal', country: 'CA' },
    GRU: { name: 'Guarulhos', city: 'São Paulo', country: 'BR' },
    EZE: { name: 'Ezeiza', city: 'Buenos Aires', country: 'AR' },
    MEX: { name: 'Benito Juárez', city: 'Mexico City', country: 'MX' },
    JNB: { name: 'OR Tambo', city: 'Johannesburg', country: 'ZA' },
    CPT: { name: 'Cape Town', city: 'Cape Town', country: 'ZA' },
    NBO: { name: 'Jomo Kenyatta', city: 'Nairobi', country: 'KE' },
    CAI: { name: 'Cairo', city: 'Cairo', country: 'EG' },
    ADD: { name: 'Addis Ababa Bole', city: 'Addis Ababa', country: 'ET' },
};
