import type { Flight, AirportCondition, Alert } from './types'

export const flights: Flight[] = [
  {
    id: '1',
    flightNumber: 'BA 0178',
    airline: 'British Airways',
    origin: 'LHR',
    destination: 'LAX',
    aircraft: 'Boeing 777',
    duration: '10h 35m',
    scheduledDeparture: '09:15',
    scheduledArrival: '12:50',
    status: 'on-time',
  },
  {
    id: '2',
    flightNumber: 'EK 0031',
    airline: 'Emirates',
    origin: 'DXB',
    destination: 'JFK',
    aircraft: 'A380',
    duration: '13h 55m',
    scheduledDeparture: '14:20',
    actualDeparture: '14:20',
    scheduledArrival: '19:45',
    actualArrival: '+38 min',
    delayMinutes: 38,
    status: 'delayed',
  },
  {
    id: '3',
    flightNumber: 'LH 0400',
    airline: 'Lufthansa',
    origin: 'FRA',
    destination: 'SIN',
    aircraft: 'A350',
    duration: '12h 20m',
    scheduledDeparture: '11:45',
    scheduledArrival: '06:05',
    nextDayArrival: true,
    status: 'landed',
  },
  {
    id: '4',
    flightNumber: 'AA 0100',
    airline: 'American',
    origin: 'JFK',
    destination: 'LHR',
    aircraft: 'Boeing 777',
    duration: '7h 00m',
    scheduledDeparture: '22:15',
    actualDeparture: '22:15',
    scheduledArrival: '10:15',
    actualArrival: '+56 min',
    delayMinutes: 56,
    nextDayArrival: true,
    status: 'delayed',
  },
  {
    id: '5',
    flightNumber: 'QF 0001',
    airline: 'Qantas',
    origin: 'SYD',
    destination: 'LAX',
    aircraft: 'A380',
    duration: '13h 30m',
    scheduledDeparture: '16:00',
    scheduledArrival: '12:30',
    status: 'boarding',
  },
  {
    id: '6',
    flightNumber: 'BA 0117',
    airline: 'British Airways',
    origin: 'LHR',
    destination: 'JFK',
    aircraft: 'Boeing 747',
    duration: '',
    scheduledDeparture: '',
    scheduledArrival: '',
    status: 'cancelled',
  },
]

export const airports: AirportCondition[] = [
  {
    code: 'LHR',
    name: 'Heathrow',
    city: 'London',
    country: 'UK',
    status: 'delays',
    conditions: 'Ground delay · avg 42 min · Wind 28 kt',
    depOnTime: 68,
    arrOnTime: 71,
  },
  {
    code: 'JFK',
    name: 'JFK',
    city: 'New York',
    country: 'USA',
    status: 'normal',
    conditions: 'No significant delays · Clear skies',
    depOnTime: 91,
    arrOnTime: 88,
  },
  {
    code: 'DXB',
    name: 'Dubai',
    city: 'UAE',
    country: 'UAE',
    status: 'normal',
    conditions: 'Ops normal · 38°C · Haze advisory',
    depOnTime: 84,
    arrOnTime: 86,
  },
]

export const alerts: Alert[] = [
  {
    id: '1',
    type: 'delay',
    message: 'EK 0031 delayed 38 min · New departure 15:02 from gate B14',
    time: 'Today 13:44',
    flightNumber: 'EK 0031',
  },
  {
    id: '2',
    type: 'cancellation',
    message: 'BA 0117 cancelled · LHR → JFK · Rebooking options available',
    time: 'Today 12:20',
    flightNumber: 'BA 0117',
  },
  {
    id: '3',
    type: 'landing',
    message: 'LH 0400 landed at SIN · Gate C32 · Baggage belt 7',
    time: 'Today 06:08 local',
    flightNumber: 'LH 0400',
  },
]
